name: Deploy Application

on:
  push:
    branches:
      - main

env:
  HARBOR_REGISTRY: whale.oognuyh.com
  IMAGE_NAME: 10daysonly/ringly

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: docker/login-action@v3
        with:
          registry: ${{ env.HARBOR_REGISTRY }}
          username: ${{ secrets.HARBOR_USERNAME }}
          password: ${{ secrets.HARBOR_PASSWORD }}

      - uses: docker/setup-buildx-action@v3

      - uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ env.HARBOR_REGISTRY }}/${{ env.IMAGE_NAME }}:latest
          build-args: |
            NEXT_PUBLIC_API_URL=https://ringly-api.oognuyh.com

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: appleboy/ssh-action@v1.2.0
        env:
          HARBOR_REGISTRY: ${{ env.HARBOR_REGISTRY }}
          IMAGE_NAME: ${{ env.IMAGE_NAME }}
        with:
          host: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_PORT }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          envs: HARBOR_REGISTRY,IMAGE_NAME
          script: |
            docker login ${HARBOR_REGISTRY} -u ${{ secrets.HARBOR_USERNAME }} -p ${{ secrets.HARBOR_PASSWORD }}
            docker pull ${HARBOR_REGISTRY}/${IMAGE_NAME}:latest
            docker ps -a | grep ringly && docker stop ringly || true
            docker ps -a | grep ringly && docker rm ringly || true

            docker run -d --name ringly \
              -p 3000:3000 \
              ${HARBOR_REGISTRY}/${IMAGE_NAME}:latest
